### PR TITLE
CI

### PR DESCRIPTION
**Pull request by PJvanVliet**
This pull request should solve issue #45 .
Code gets linted with flake8 and tested with unittest in pipenv.

### CODE REVIEW

**Comment by PJvanVliet** [comment]
Currently, still has issues with flake8. There are a few undefined names.

**Comment by Drvanon** [comment]
I don't think running it with flake is very sensible as we have not kept our code flake8 compliant. We could, and it might be good, but it is not necessary. What is more necessary is that tests pass.

**Comment by PJvanVliet** [comment]
The dependencies are still not installed, causing errors.

**Comment by Drvanon** [comment]
I think you are forgetting to install the pipenv dependencies.

**Comment by marickmanrho** [comment]
I think the flake8 is not hard to implement, you have tools which automatically structure the code to be flake8 compliant (e.g. black). The [output](https://github.com/GridtNetwork/gridt-server/pull/62/checks?check_run_id=1075468017) does say the dependencies defined in the piplock file are installed, however then the error messages suggest that the packages are not there. Hence I expect the piplock file to be incomplete.

**Comment by marickmanrho** [comment]
Actually, upon closer inspection, It doesn't find the piplock file...

**Comment by Drvanon** [comment]
>...you have tools which automatically structure the code to be flake8 compliant (e.g. black)
We actually always run black before committing, but maybe we run it with settings that are not necessarily PEP8 compliant.

>  Actually, upon closer inspection, It doesn't find the piplock file...
This might be because the actual python directory is in /web.

**Comment by PJvanVliet** [comment]
> > ...you have tools which automatically structure the code to be flake8 compliant (e.g. black)
> 
> We actually always run black before committing, but maybe we run it with settings that are not necessarily PEP8 compliant.
> 
> > Actually, upon closer inspection, It doesn't find the piplock file...
> 
> This might be because the actual python directory is in /web.

Thanks! Will update accordingly.

**Comment by Drvanon** [comment]
I think you have to set an environment variable.

**Comment by Drvanon** [comment]
Woop!

**Pull request merged**
